Toggle test simulation.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -19,15 +19,15 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Simulate successful test run
-        run: |
-          echo "Test run successful!"
-          exit 0
-
-      # - name: Simulate failed test run
+      # - name: Simulate successful test run
       #   run: |
-      #     echo "Test run failed!"
-      #     exit 1
+      #     echo "Test run successful!"
+      #     exit 0
+
+      - name: Simulate failed test run
+        run: |
+          echo "Test run failed!"
+          exit 1
 
       # - name: Test
       #   run: |
